import { Geist, Geist_Mono } from "next/font/google";
import { Bayon } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bayon = Bayon({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bayon",
});

export const metadata = {
  title: "Janta Power",
  icons: {
    icon: '/images/favicon.ico',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bayon.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
